openapi: 3.0.0
info:
  title: Documents Service API
  version: 1.0.0
  description: API for managing patient history documents.
servers:
  - url: http://localhost:5000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    History:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
        pacientId:
          type: integer
        hospitalId:
          type: integer
        doctorId:
          type: integer
        room:
          type: string
        data:
          type: string


security:
  - bearerAuth: []

paths:
  /api/History/Account/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Account ID
    get:
      summary: Get account history
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Account history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/History'
        '403':
          description: Access denied
        '404':
          description: History not found

  /api/History:
    post:
      summary: Create history entry
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/History'
      responses:
        '201':
          description: History created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  message:
                    type: string
        '500':
          description: Failed to create history


  /api/History/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: History ID
    get:
      summary: Get history entry
      security:
        - bearerAuth: []
      responses:
        '200':
          description: History entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/History'
        '403':
          description: Access denied
        '404':
          description: History not found
    put:
      summary: Update history entry
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/History'
      responses:
        '200':
          description: History updated successfully
        '500':
          description: Failed to update history